### ISSUE TITLE
Abfallkalender für Reichenbach an der Fils

### ISSUE THREAD

**Issue by ragman1976** [florianzeeb/awb-es#1]
Hallo,

ich versuche den Abfallkalender für Reichenbach/fils über den ical Adapter in ioBroker einzubinden. Leider funktioniert das mit der Originaladresse nicht. Wäre es möglich den Kalender für Reichenbach in dein Projekt aufzunehmen?

**Comment by florianzeeb** [comment]
Hallo @ragman1976, gerne doch und ich hoffe das löst dein Problem ;)

https://raw.githubusercontent.com/florianzeeb/awb-es/master/awb-es_ical_reichenbach_fils.ics

**Comment by ragman1976** [comment]
> Hallo @ragman1976, gerne doch und ich hoffe das löst dein Problem ;)
> 
> https://raw.githubusercontent.com/florianzeeb/awb-es/master/awb-es_ical_reichenbach_fils.ics

Besten Dank!
